#include "totvs.ch"

/*/{Protheus.doc} VRPO
Rotina que retorna versao do RPO para gravar na tabela "PBK".
Controle de versao de RPO especifico da MM da Amazonia.
@type function
@version 1.0 
@author DO THINK - FERNANDO MUTA
@since 05/02/2025
@obs 20241209_1041_PRD, onde:
2024 (Ano) + 12 (Mes) + 09 (Dia) + _ + 10 (Hora) + 41 (Minuto) + _ + PRD (Ambiente: PRD, HOM, DEV, etc.)
/*/
User Function VRPO()
Return "20260723_1155_PRD"
